In [21]:
import cv2

In [192]:
image = cv2.imread(r'C:\Users\knataraj\Desktop\swan.jpg')

In [23]:
image.shape

(768, 1024, 3)

In [120]:
cv2.namedWindow('image', cv2.WINDOW_NORMAL)
cv2.imshow('image',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [25]:
image[0][0][0]


12

In [26]:
image[0][0]


array([12,  6,  1], dtype=uint8)

In [27]:
image[0]

array([[12,  6,  1],
       [12,  6,  1],
       [12,  6,  1],
       ...,
       [10,  6,  1],
       [10,  6,  1],
       [10,  6,  1]], dtype=uint8)

In [36]:
image[0:100] = (255, 255, 255)
image[1:100] = (255, 255, 255)
image[2:100] = (255, 255, 255)
image[3:100] = (255, 255, 255)
image[4:100] = (255, 255, 255)


In [37]:
image

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[  1,   1,   1],
        [  1,   1,   1],
        [  1,   1,   1],
        ...,
        [ 11,   7,   2],
        [  9,   6,   2],
        [  9,   6,   2]],

       [[  1,   1,   1],
        [  1,   1,   1],
        [  1,   1,   1],
        ...,
        [ 10,   6,   1],
        [  9,   6,   2],
        [  9,   6,   2]],

       [[  1,   1,   1],
        [  1,   1,   1],
        [  2,   2,   2],
        ...,
        [ 10,   6,   1],
        [  9,   6,   2],
        [  8,   5,   1]]

In [38]:
image

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[  1,   1,   1],
        [  1,   1,   1],
        [  1,   1,   1],
        ...,
        [ 11,   7,   2],
        [  9,   6,   2],
        [  9,   6,   2]],

       [[  1,   1,   1],
        [  1,   1,   1],
        [  1,   1,   1],
        ...,
        [ 10,   6,   1],
        [  9,   6,   2],
        [  9,   6,   2]],

       [[  1,   1,   1],
        [  1,   1,   1],
        [  2,   2,   2],
        ...,
        [ 10,   6,   1],
        [  9,   6,   2],
        [  8,   5,   1]]

In [50]:
len(image[767])

1024

In [61]:
image[0:100, 100:500] = (255, 255, 122)

In [69]:
image[0,0,0]=100

In [104]:
image.shape

(768, 1024, 3)

In [105]:
image[767,0,0] = 56

In [106]:
image

array([[[100,  10,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[100,  10,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[100,  10,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,  56]],

       ...,

       [[  1,   1,   1],
        [  1,   1,   1],
        [  1,   1,   1],
        ...,
        [ 11,   7,   2],
        [  9,   6,   2],
        [  9,   6,   2]],

       [[  1,   1,   1],
        [  1,   1,   1],
        [  1,   1,   1],
        ...,
        [ 10,   6,   1],
        [  9,   6,   2],
        [  9,   6,   2]],

       [[ 56,   1,   1],
        [  1,   1,   1],
        [  2,   2,   2],
        ...,
        [ 10,   6,   1],
        [  9,   6,   2],
        [  8,   5,   1]]

In [97]:
image

array([0, 0, 0], dtype=uint8)

In [94]:
image[0][0]

array([100,  10,   0], dtype=uint8)

In [126]:
image[150:500, 500:800, 10:20] =(0)

In [127]:
cv2.namedWindow('image', cv2.WINDOW_NORMAL)
cv2.imshow('image',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [128]:
image

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [ 10,   6,   1],
        [ 10,   6,   1],
        [ 10,   6,   1]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [ 10,   6,   1],
        [ 10,   6,   1],
        [ 10,   6,   1]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [ 10,   6,   1],
        [ 10,   6,   1],
        [ 10,   6,   1]],

       ...,

       [[  1,   1,   1],
        [  1,   1,   1],
        [  1,   1,   1],
        ...,
        [ 11,   7,   2],
        [  9,   6,   2],
        [  9,   6,   2]],

       [[  1,   1,   1],
        [  1,   1,   1],
        [  1,   1,   1],
        ...,
        [ 10,   6,   1],
        [  9,   6,   2],
        [  9,   6,   2]],

       [[  1,   1,   1],
        [  1,   1,   1],
        [  2,   2,   2],
        ...,
        [ 10,   6,   1],
        [  9,   6,   2],
        [  8,   5,   1]]

In [130]:
bird = image[120:500, 400:800]

In [143]:
cv2.namedWindow('bird1', cv2.WINDOW_NORMAL)
cv2.imshow('bird1', canvas1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [133]:
bird.shape    

(380, 400, 3)

In [134]:
import numpy as np

In [138]:
canvas = np.ones((300,300,3), dtype = 'uint8')

In [142]:
canvas1 = np.ones((300,300,3), dtype = 'uint8')

In [155]:
green = (255,255,255)
cv2.line(canvas, (200,0), (0,200), green, 5)
cv2.namedWindow('bird1', cv2.WINDOW_NORMAL)
cv2.imshow('bird1', canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
### cv2.rectangle(canvas, (0,0),(100,100), green, -1)
cv2.namedWindow('bird1', cv2.WINDOW_NORMAL)
cv2.imshow('bird1', canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [174]:
def reverse(string): 
    if len(string) == 0: 
        print('if')
        return
      
    temp = string[0] 
     
    #print(temp, end='')
   # print('--')
    #print(string[1:])
    reverse(string[1:])
    #print(temp, end='')
    
reverse('Chethan')

if


In [168]:
a = 'abc'

b = a[0]
b=a[1]

print(b)

b


In [191]:
canvas = np.zeros((300,300, 3), dtype = 'uint8')
(X, Y) = (canvas.shape[1] //2, canvas.shape[0]//2)

for i in range(0, 122):
    r = np.random.randint(0, high = 150)
    color = np.random.randint(0, high=256, size=(3,)).tolist()
    pt = np.random.randint(0, high=600, size = (2,))
    cv2.circle(canvas, tuple(pt),r, color, -1)

cv2.namedWindow('bird1', cv2.WINDOW_NORMAL)
cv2.imshow('bird1', canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [195]:
matrix = np.float32([[1,0,-50],[0,1,-100]])
shifted = cv2.warpAffine(image, matrix, (image.shape[1], image.shape[0]))


cv2.namedWindow('bird1', cv2.WINDOW_NORMAL)
cv2.imshow('bird1', shifted)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [201]:
image = cv2.imread(r'C:\Users\knataraj\Desktop\swan.jpg')

(h,w) = image.shape[:2]

center = (w//2, h//2)

matrix = cv2.getRotationMatrix2D(center, -90, 2.0)
shifted = cv2.warpAffine(image, matrix, (w, h))

cv2.namedWindow('bird1', cv2.WINDOW_NORMAL)
cv2.imshow('bird1', shifted)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [215]:
image = cv2.imread(r'C:\Users\knataraj\Desktop\swan.jpg')
r = (11115.0 /image.shape[1])

dim = (11115, int(image.shape[0]*r))

resized = cv2.resize(image, dim, interpolation = cv2.INTER_AREA)
cv2.namedWindow('resized', cv2.WINDOW_NORMAL)
cv2.imshow('resized', resized)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [230]:
blur = cv2.bilateralFilter(image, 111, 17, 21)
cv2.namedWindow('blur', cv2.WINDOW_NORMAL)
cv2.imshow('blur', blur)
cv2.waitKey(0)
cv2.destroyAllWindows()